description = c("Participated in Head Start",
                "Different HS Participation from Sibling",
                "Unique Mother Identifier n from Sibling",
                "Non-Black Hispanic ifier n from Sibling",
                "Black ack Hispanic ifier n from Sibling",
                "Male  ack Hispanic ifier n from Sibling",
                "1st-Born Sibling c ifier n from Sibling",
                "Log HH Income, Ages 0 to 3 from Sibling",
                "Mother's Years of Education rom Sibling",
                "Living with Father, Ages 0 to 3 Sibling",
                "PPVT Score, Age 3 , Ages 0 to 3 Sibling",
                "Log Birth Weight  , Ages 0 to 3 Sibling",
                "Composite Test Score, Age 5-6 3 Sibling",
                "Composite Test Score, Age 7-10  Sibling",
                "Composite Test Score, Age 11-14 Sibling",
                "Repeated a Grade ore, Age 11-14 Sibling",
                "Learning Disability , Age 11-14 Sibling",
                "High Schol Graduate , Age 11-14 Sibling",
                "Attended Some College Age 11-14 Sibling",
                "Idle ded Some College Age 11-14 Sibling",
                "Self-Rated Fair/Poor Health -14 Sibling",
                "Self-Rated Fair/Poor Health -14 Sibling")
